Feature/homework 6
nastja123456789/groupie pull request #5
Opened 2022-12-22 13:26 UTC by nastja123456789

2023-01-10 21:54 UTC, AndroidStudentClub requested changes
Проверил

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/Extension.kt
> +        const val API_KEY = "38021fe5bd0d26b759953028cf30ab6d"
Не, api key надо в properties.keystore хранить и потом вычитывать из build.gradle

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/CommonFeedQuery.kt
> +class CommonFeedQuery(ratedMovie: MoviesResponse, playMovie: MoviesResponse) {
Тут можно сделать немного по-другому. Например сделать так - чтобы результат zip был бы например HashMap<key,value> где ключ например поле из Enum(POPULAR,UPCOMING) etc, а значение список.
Потом сделать метод который будет принимать этот map и уже там конвертировать ячейки в Items.
Потому что в текщуем варианте если будет 10 категорий - то будет 10 таких полей

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +        val ratedMovie = MovieApiClient.apiClient.getTopRatedMovies(Extension.API_KEY,Extension.language)
В дефолтные аргументы в интерефейс ретрофита можно вынести

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +            io.reactivex.functions.BiFunction<MoviesResponse, MoviesResponse, CommonFeedQuery> {
Вот про это писал, что можно сделать HashMap вместо объекта с полями. Объект с полями не красиво - потому что не масштабируется

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +            .observeOn(AndroidSchedulers.mainThread())
Вот это повторяется, можно вынести например в extension - чтобы не писать постоянно оба оператора

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +                                    MovieItem(it2!!) {movie ->
Оператор !! лучше не использовать

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +                            MainCardContainer(
Вот эта логика повторяется - можно сделать метод, который на входе принимает заголовок, а на выходе отдает ячейку, а внутри производит конвертацию

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +                                    MovieItem(it2!!) {movie ->
Оператор !! лучше не использовать

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +            binding.moviesRecyclerView.adapter = adapter.apply { removeGroup(0) }
да раза - вроде лишнее, там достаточно adapter.clear

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/MovieApiClient.kt
> +    const val BASE_URL = "https://api.themoviedb.org/3/"
Уже кажется писал про это:
В целом, хорошей практикой является вынесение базового урл в build.gradle 

Это может пригодится, когда у нас разные урл (например один для тестового билда/второй для настоящего который в проде)

Вот статья на эту тему [https://medium.com/@ramonrabello/best-practices-for-working-with-different-build-types-c5cd08b1adc6](https://medium.com/@ramonrabello/best-practices-for-working-with-different-build-types-c5cd08b1adc6)Смотреть пункт [#3](https://github.com/dfyz8-g/MoviesApp/pull/3) Way: Using Gradle Build Config Fields

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/MovieViewModel.kt
> +    fun setLike(boolean: Boolean) {
Тут нужно в БД сохранять лайкнутые фильмы

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/TVModel.kt
> +            "https://image.tmdb.org/t/p/w500$field"
Кстати для картинки можно тоже вынести базовый урл в build.gradle 

Это может пригодится, когда у нас разные урл (например один для тестового билда/второй для настоящего который в проде)

Вот статья на эту тему [https://medium.com/@ramonrabello/best-practices-for-working-with-different-build-types-c5cd08b1adc6](https://medium.com/@ramonrabello/best-practices-for-working-with-different-build-types-c5cd08b1adc6)Смотреть пункт [#3](https://github.com/dfyz8-g/MoviesApp/pull/3) Way: Using Gradle Build Config Fields

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +        binding.likeImage.setOnClickListener {
Не совсем понятно зачем используется setOnClickListener. Если like сделать через чекбокс - то можно использовать setOnCheckedChangeListener

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                binding.likeImage.setImageResource(R.drawable.ic_heart)
Не, так точно не нужно делать

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                binding.likeImage.setImageResource(R.drawable.ic_heart)
Тут нужно использовать CheckBox вместо ImageButton с кастомным селектором. Пользователь будет нажимать на сердечко - оно будет меняться на заполненное. Подробнее можно посмотреть тут https://stackoverflow.com/questions/3192173/change-icons-of-checked-and-unchecked-for-checkbox-for-android

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                lifecycleScope.launch(Dispatchers.IO) {
Ну, можно и через корутины.

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                    MovieRoomDatabase.getDatabase(requireContext()).movieDao().delete(MovieModelDB(image!!))
Оператор !! может служить причиной краша

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchMoviesAdapter.kt
> +        Picasso.get()
Вот этот код повторяется - можно сделать проще, написав один раз extension для ImageView внутри которого будет эта логика. В итоге будет что-то типа imagePreview.loadImage(url)

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchMoviesAdapter.kt
> +        holder.rating.text = current.voteAverage!!.toString()
Оператор !!

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/Movie.kt
> +        Picasso.get()
Вот этот код повторяется - можно сделать проще, написав один раз extension для ImageView внутри которого будет эта логика. В итоге будет что-то типа imagePreview.loadImage(url)

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowsFragment.kt
> +            .subscribeOn(Schedulers.io())
Вот это повторяется, можно вынести например в extension - чтобы не писать постоянно оба оператора

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowsFragment.kt
> +        val call = MovieApiClient.apiClient.getPopularTV(Extension.API_KEY, Extension.language)
Extension.API_KEY, Extension.language можно вынести в дефолтные аргументы

2023-01-10 21:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowsFragment.kt
> +        val call = MovieApiClient.apiClient.getPopularTV(Extension.API_KEY, Extension.language)
Кстати почему название Extension? Это же просто константы

2023-01-28 13:02 UTC, merged

2023-01-28 13:03 UTC, nastja123456789 commented
close 6